yapt:
  device_type: srx
  device_group: srx
  service_chain: []
  bootstrap_template_dir: conf/vnf/template
  bootstrap_template_file: vsrx_ztp_bootstrap.j2

device:
  hostname: vsrx_ztp01
  encrypted_password: $5$Wbt5G9uy$IW32MqVW.3.sxbrz0jzs4X/JrTAbNk1E41N9.lMO0j5
  ossh_secret: $9$m5zntu1ylM/ClM8XbwmfT
  timezone: Europe/Berlin
  domain_name: mycompany.local
  ntp_server: 192.168.2.1
  community: public
  interfaces:
  - name: ge-0/0/0
    description: untrust
    family: inet
    address: dhcp
  - name: ge-0/0/1
    description: trust
    family: inet
    address: dhcp
  cert:
    ca_profile: ejbca
    ca_identity: advpn
    subject: CN=vsrx_ztp01,OU=IT,O=MyCompany,L=Berlin,DC=mycompany.local,C=DE
    domain_name: vsrx_ztp01.mycompany.local
    enrollment_url: ejbca/publicweb/apply/scep/advpn/pkiclient.exe
    oscp_url: ejbca/publicweb/status/ocsp
    challenge_password: juniper123
    revocation_url: ejbca/publicweb/status/ocsp