yapt:
    device_type: nfx
    device_group: nfx
    service_chain: []

device:
    hostname: nfx250-01
    timezone: Europe/Berlin
    domain_name: mycompany.local
    ntp_server: 10.1.1.1
    encrypted_password: $1$AjvjSnDw$QrTngM5tI.IqliertjQhb/
    community: public
    interfaces:
      - name: jsxe0
        description: management
        family: inet
        address: dhcp
    host_os_vlans:
      - name: left
        id: 100
      - name: right
        id: 200
      - name: untrust
        id: 1
    vnfs:
      - name: vsrx_ztp01
        vnf_type: juniper
        base_img_path: /var/third-party/images/
        base_img: media-vsrx-vmdisk-15.1X49-D100.6.qcow2
        bootstrap_remote_dir: /var/third-party/bootstrap/
        deviceID: 1WB6PTXYRG9Z
        interfaces:
          - name: eth4
            description: untrust
            mapping: hsxe0
          - name: eth5
            description: trust
            mapping: hsxe1