yapt:
  device_type: srx
  device_group: srx
  service_chain: []
  bootstrap_template_dir: conf/vnf/template
  bootstrap_template_file: vsrx_ztp_bootstrap.j2

device:
  hostname: vsrx_ztp01
  encrypted_password: $5$q24sOtoE$48sYy4JYG9fe3Q4PN/aZskulTHlI1KfIG.PiszMwVv0
  ossh_secret: $9$m5zntu1ylM/ClM8XbwmfT
  timezone: Europe/Berlin
  domain_name: mycompany.local
  ntp_server: 10.21.28.2
  community: public
  interfaces:
  - name: fxp0
    description: MGMT
    family: inet
    address: dhcp
  - name: ge-0/0/0
    description: MGMT
    family: inet
    address: dhcp
  - name: ge-0/0/1
    description: untrust
    family: inet
    address: dhcp
  - name: ge-0/0/2
    description: trust
    family: inet
    address: 10.12.112.254
    mask: 24
  tunnel_int:
    name: st0
    description: VPN
    unit: 0
    family: inet
    address: ipam
    mask: 24
  cert:
    ca_profile: ejbca
    ca_identity: advpn
    subject: CN=vsrx_ztp01,OU=IT,O=MyCompany,L=Berlin,DC=mycompany.local,C=DE
    domain_name: vsrx_ztp01.mycompany.local
    enrollment_url: ejbca/publicweb/apply/scep/advpn/pkiclient.exe
    oscp_url: ejbca/publicweb/status/ocsp
    challenge_password: juniper123
    revocation_url: ejbca/publicweb/status/ocsp