{
	"version": 1,
	"formatters": {
		"void": {
			"format": ""
		},
		"standard": {
			"format": "%(asctime)s - [%(name)s] --- %(message)s",
			"datefmt": "%Y-%m-%d %H:%M:%S"
		}
	},
	"handlers": {
		"default": {
			"level": "INFO",
			"class": "logging.StreamHandler",
			"formatter": "standard",
			"stream": "ext://sys.stdout"
		},
		"yapt_console": {
			"level": "INFO",
			"class": "logging.StreamHandler",
			"formatter": "standard",
			"stream": "ext://sys.stdout"
		},
		"yapt_info": {
			"level": "INFO",
			"class": "logging.handlers.RotatingFileHandler",
			"formatter": "standard",
			"filename": "logs/info.log",
			"maxBytes": 10485760,
			"backupCount": 10,
			"encoding": "utf8"
		},
		"yapt_debug": {
			"level": "DEBUG",
			"class": "logging.handlers.RotatingFileHandler",
			"formatter": "standard",
			"filename": "logs/debug.log",
			"maxBytes": 10485760,
			"backupCount": 10,
			"encoding": "utf8"
		},
		"cherrypy_console": {
			"level": "INFO",
			"class": "logging.StreamHandler",
			"formatter": "void",
			"stream": "ext://sys.stdout"
		},
		"cherrypy_access": {
			"level": "INFO",
			"class": "logging.handlers.RotatingFileHandler",
			"formatter": "void",
			"filename": "logs/access.log",
			"maxBytes": 10485760,
			"backupCount": 10,
			"encoding": "utf8"
		},
		"cherrypy_error": {
			"level": "INFO",
			"class": "logging.handlers.RotatingFileHandler",
			"formatter": "void",
			"filename": "logs/errors.log",
			"maxBytes": 10485760,
			"backupCount": 10,
			"encoding": "utf8"
		},
		"paramiko_info": {
			"level": "INFO",
			"class": "logging.handlers.RotatingFileHandler",
			"formatter": "void",
			"filename": "logs/paramiko.log",
			"maxBytes": 10485760,
			"backupCount": 10,
			"encoding": "utf8"
		}
	},
	"loggers": {
		"": {
			"handlers": ["default"],
			"level": "INFO"
		},
		"YAPT.INFO": {
			"handlers": ["yapt_console", "yapt_info"],
			"level": "INFO",
			"propagate": false
		},
		"YAPT.DEBUG": {
			"handlers": ["yapt_console", "yapt_debug"],
			"level": "DEBUG",
			"propagate": false
		},
		"cherrypy.access": {
			"handlers": ["cherrypy_access"],
			"level": "INFO",
			"propagate": false
		},
		"cherrypy.error": {
			"handlers": ["cherrypy_error"],
			"level": "INFO",
			"propagate": false
		},
		"paramiko.transport": {
			"handlers": ["paramiko_info"],
			"level": "INFO",
			"propagate": false
		}
	},
    "root": {
        "handlers": [
          "yapt_console"
        ],
        "level": "INFO"
    }
}