---
#**********************************************************************************************************************
#GROUP: VMX
#***********************************************************************************************************************

########################################################################################################################
#Tasks Section (turn on/off provisioning tasks / configure specific task settings)
########################################################################################################################
TASKS:
  #Enable provision tasks and set processing order within sequence
  #Sequence: Init, Filecp, Software, Ipam, Configuration, Cert, Discovery, Policy, Assign, Rule, Publish, Cleanup
  Sequence: [Init, Configuration, Cleanup]

  Provision:

    Init:
      Dependencies: [Configuration, Software]

    Configuration:
      DeviceConfTemplateDir: conf/devices/template/   #device specific template config directory
      DeviceConfTemplateFile: vmx_no_ipam.j2          #device config template name
      ConfigFileHistory: history/                     #path to dir where commited device config being saved
      Merge: True                                     #Merge Configuration
      Overwrite: False                                #Replace Configuration

      Internal:
        CommitTimeout: 120                            #Set Commit Timeout to x sec
        ConfirmedTimeout: 5                           #Set Commit confirmed timeout to x min

      Ansibleapi:
        PlaybookPath: conf/ansible/playbooks/         #Set path to playbook
        Playbook: yapt_playbook.yml                   #Set Playbook file name. Playbooks stored in conf/ansible/playbook

    Cert:
      PortForwarding: True                                          #Enable Port Forwarding for cert retrieval
      LocalFwdPort: 5554                                            #Forwarding Port on device
      RemoteFwdHost: 172.16.146.136                                 #Remote host to forward to
      RemoteFwdHostPort: 8080                                       #Port on remote host to forward to
      EnrollmentUrl: ejbca/publicweb/apply/scep/advpn/pkiclient.exe #
      RevocationUrl: ejbca/publicweb/status/ocsp                    #

    Discovery:
      Mode: Discovery                                 #Set discovery mode to either Discovery or Configlet
      ConnectionConfigletDir: conf/configlet/         #modeled device configlet file path

    Filecp:
      File: [ADVPNCertRollout.slax]                   #File to be copied to device (e.g. SLAX)
      FileLocalDir: scripts/                          #source directory where to find files (defaults to script dir)
      FileRemoteDir: /var/db/scripts/event            #Event/Commit/OP Script or any other directory path on device

    Ipam:
      Module: nipap
      Address: 10.15.115.6
      Port: '1337'
      Prefixes: [10.200.0.0/24, 10.13.113.0/24]
      User: nipap
      Password: nipap

    Software:
      ImageDir: images/                               #device software images directory
      RemoteDir: /var/tmp/                            #destination directory
      RebootProbeCounter: 30                          #How many times probe should be send while dev rebooting
      RebootProbeTimeout: 30                          #wait n sec starting probing after device is rebooted
      RetryProbeCounter: 5                            #How many times probe should be send while going into reboot
      PkgAddDevTimeout: 1800                          #Timeout for pkgadd function (OSSH)

      TargetVersion:
        VMX: 17.1R2.7

    Ticket:
      Module: Rt                                                  #Module currently only request_tracker ticketing system
      Mode: detail                                                #Mode could be "summary" to give a summarization at the end or "detail" to get update after every task

      Rt:
        Address: 10.86.9.14                                         #Ticket System IP address
        Port: 8000                                                  #Ticket System Port
        Protocol: https                                             #HTTP / HTTPS
        User: juniper                                               #Ticket system user
        Password: juniper123                                        #Ticket system passsword
        Eauth: pam                                                  #EDI authentication module
        Functions: [request_tracker.create_ticket, request_tracker.update_ticket]   #call edi runner functions
        NextEvent: None                                             #
        TemplateDir: lib/emitter/templates/                         #Template directory
        TicketCreateTemplate: ticket_create_detail_mode.j2          #Template file used for tickte creation
        TicketUpdateTemplate: ticket_update_detail_mode.j2          #Template file used for ticker update

########################################################################################################################
#Verification Task Section
########################################################################################################################
  Verification:

    Ping:
      Destination: 10.12.111.1
      Count: '10'

    Vpn:
      SaRemoteAddress: 10.11.111.115

    Jsnapy:
      ConfigFileDir: conf/jsnapy/
      ConfigFile: config_snapcheck.yml